### ISSUE TITLE
Simplify `x |> (\y -> f y)` into `f x`

### ISSUE THREAD

**Issue by lydell** [jfmengels/elm-review-simplify#111]
I had some code like this:

```elm
example =
    [ Just label
    , info
    ]
        |> List.filterMap identity
        |> List.concatMap
            (\template ->
                template.children
            )

```

During a refactor, I removed `info` from the list, which was correct and compiles.

```diff
 example =
     [ Just label
-    , info
     ]
         |> List.filterMap identity
         |> List.concatMap
             (\template ->
                 template.children
             )
 
```

elm-review nicely notices that the `filterMap` and `concatMap` are unnecessary now:

```elm
example =
    label
        |> (\template ->
                template.children
           )
```

However, piping a variable to a lambda is unnecessary too. I could simplify it to:

```elm
example =
    label.children
```

After that, I happened to stumble on the same pattern in the wild:

- https://github.com/dillonkearns/elm-markdown/blob/7.0.1/src/Markdown/Renderer.elm#L370-L372
- https://github.com/dillonkearns/elm-markdown/blob/7.0.1/src/Markdown/Renderer.elm#L404-L405

So I think there’s potential for more simplifications here!

I think the pattern we are looking for is:

- A simple identifier (lets call it `x`)
- Piped to a lambda
- Whose first pattern is also a simple identifier (lets call it `y`)

Then we can get rid of the lambda and substitute `y` into `x`.

Examples:

- `x |> (\y -> f y)` -> `f x`
- `x |> (\y -> y.p)` -> `x.p`
- `x |> (\y z -> y + z)` -> `\z -> x + z`

What do you think?

**Comment by jfmengels** [comment]
I've noticed this as well (as `someExpression |> (\y -> f y)` and `(\y -> f y) someExpression`).

I am still torn on this one though, because I can imagine it to turn into something a bit hard to read if the expression is a bit long or the lambda a bit complex.

I don't think I have any problems with this proposal if we only apply it in the limited section that you're thinking of where we have a simple identifier passed as an argument to the lambda function (piped or not). We can then try to extend it more later.

I do feel like I see the pattern a bit more often with a value like `a.b.c` (where `a` is a simple identifier), which I could could work too, even if introducing `a.b.c` might be a bit longer than `y` in terms of number of characters. For this one, the only worry should be to avoid the simplification if we see `{ y | ... = ... }` as that will introduce a compiler error.

---

Maybe one thing that keeps me a little bit on the fence is whether this is the best simplification. Because for `x |> (\y -> f y)` there are multiple very valid ways to simplify the problem:

```elm
-- Original
value = x |> (\y -> f y)

-- 1 - your proposal
value = f x

-- 2 - simplify the lambda
value = x |> f

-- 2 - Extract to a function
value = x |> newFunction
newFunction y = f y
```
