### ISSUE TITLE
Eta reduce lambdas

### ISSUE THREAD

**Issue by SiriusStarr** [jfmengels/elm-review-simplify#13]
(Continuing my spam of bad code examples from an old project of mine, sorry...)  Eta reduction in general is somewhat contentious, since some prefer a more verbose style in Elm, but eta reduction of lambdas seems a pretty reasonable simplification to make, i.e.

```elm
List.map (\x -> f x) xs
```

to

```elm
List.map f xs
```

**Comment by jfmengels** [comment]
I remember other people suggesting the same thing. I personally don't believe that this would always be necessarily better, because the name that you give to the variable can help you understand the code.


```elm
someData
  |> someFunction_1
  |> List.map someFunction_2
```

For instance, in the example above, it may not immediately clear what `someFunction_1` does and what it returns. Similarly, it is not obvious what `someFunction_2` may do. Of course, this is an issue with bad names and giving great names would be better. But sometimes we're using generic functions and complex function applications and it becomes hard to understand even in more real world examples and legible names.

Now let's take the same example but with a lambda around `someFunction_2`:

```elm
someData
  |> someFunction_1
  |> List.map (\user -> someFunction_2 user)
```

In this case, even if the individual functions' names are not clear, we can infer that `someFunction_1` returns a List of "user" and that `someFunction_2` somehow deals with users.

I would not likely add a lambda around `someFunction_2` on my own, but removing it does not always feel like a 100% win in my opinion.

I'll close this because I don't see myself adding this rule in this package at this point in time, but feel free to disagree and reply :)

**Comment by SiriusStarr** [comment]
Certainly, though I feel like I often see it with `List.map (\i -> someFunction i)` which doesn't add much.  Honestly, this could maybe be good as a standalone rule, with a configuration option like `{ reduceVarsShorterThan = 3 }`, so that `List.map (\i -> someFunction i)` becomes `List.map someFunction` but ``List.map (\users -> someFunction users)` stays as is.

But that's just me pondering, not appealing the decision.  :rofl:

**Comment by jfmengels** [comment]
> But that's just me pondering

Please ponder! :blush: 

I agree that short variable names won't bring much. Except when they do like:
```elm
changeCoordinates : (Int -> Int) -> (Int -> Int) -> (Int, Int) -> (Int, Int)
changeCoordinates moveX moveY (x, y) =
    (moveX x, moveY y)

newCoordinates =
    changeCoordinates
        add2  -- is this changing x or y?
		add3  -- same question
		coordinates
-- is less clear than
newCoordinates =
    changeCoordinates
        (\x -> add2 x)
        (\y -> add3 y)
		coordinates
```
because in this instance, a one-letter coordinate *is* the best and most appropriate name :sweat_smile:

**Comment by SiriusStarr** [comment]
Fair enough, this is probably too situational to be useful.
