### ISSUE TITLE
`n * 0` isn't always `0`

### ISSUE THREAD

**Issue by lue-bird** [jfmengels/elm-review-simplify#58]
`multiplyChecks`, `listFoldrChecks`, `listFoldlChecks` use `getUncomputedNumberValue` to check for `0`. Returning `Float * 0` however does not give the correct answer for certain very rare edge cases:
```elm
 1 / 0 --> Infinity
-1 / 0 --> -Infinity
 0 / 0 --> NaN
```
which multiplied with `0` all give `NaN`.

I think the rule helps you _a lot more often_ than it bites you, so if you think a few very rare wrong fixes are the price, just close the issue.

Possible steps to improve the situation:
- only report an error without fixes or nothing at all for `Expression.Floatable 0` (This is not what `Simplify` usually does)
- keep the current behavior but try to have separate checks on NaN and Infinity (like if NaN is multiplied by something, the result is NaN)
- (suggested by @gampleman) keep the current behavior but warn about NaN in the message and suggest replacing it with an explicit check for NaN if that behaviour was the intended one

**Comment by jfmengels** [comment]
I think it makes sense to say what others (like @gampleman) mentioned on Slack: Keep the simplification but not provide a fix. I'm kind of sad to have parts of this rule not be auto-fixable, but I agree that it's for the best.

We should change this simplification but mention in the details how to change the code so that the rule stops reporting the issue. I'm not yet entirely sure what to suggest though.
